version: "3"

services:
  web:
    image: nginx:alpine
    ports:
      - 8888:8888
      - 1337:1337
    volumes:
      - ./www:/srv/www
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./conf/ping.conf:/etc/nginx/conf.d/ping.conf
    networks:
      - www
  phpfpm:
    image: php:fpm-alpine
    volumes:
      - ./www:/srv/www
      - ./conf/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./conf/php-fpm.conf:/usr/local/etc/php-fpm.conf
    networks:
      - www

networks:
  www:
